name: build_bluedhook
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=$HOME/theos
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/*.sdk $THEOS/sdks/
          mkdir -p $THEOS/include/CaptainHook
          curl -L https://raw.githubusercontent.com/rpetrich/CaptainHook/master/CaptainHook.h -o $THEOS/include/CaptainHook/CaptainHook.h

      - name: Build Package
        run: |
          export THEOS=$HOME/theos
          cd bluedhook
          
          # [核心新增]：自动修复 control 文件的换行符问题
          # 强制将 Windows 换行符 (CRLF) 转换为 Unix 换行符 (LF)
          perl -pi -e 's/\r\n/\n/g' control
          
          make package

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: bluedhook-rootless-deb
          path: bluedhook/packages/*.deb